=== silesnet/sis-legacy/src/test/resources/db-xsd/dataset.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:dflt="PUBLIC">
	<xsd:import namespace="PUBLIC" schemaLocation="PUBLIC.xsd" />
	<xsd:element name="dataset">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="SERVICES" type="dflt:SERVICES__type" />
				<xsd:element name="BILL_ITEMS" type="dflt:BILL_ITEMS__type" />
				<xsd:element name="DUAL_AUDIT_ITEM_ID_SEQ" type="dflt:DUAL_AUDIT_ITEM_ID_SEQ__type" />
				<xsd:element name="BILLS" type="dflt:BILLS__type" />
				<xsd:element name="NEWSERVICES" type="dflt:NEWSERVICES__type" />
				<xsd:element name="INVOICINGS" type="dflt:INVOICINGS__type" />
				<xsd:element name="VENDORS" type="dflt:VENDORS__type" />
				<xsd:element name="SETTINGS" type="dflt:SETTINGS__type" />
				<xsd:element name="DBMAINTAIN_SCRIPTS" type="dflt:DBMAINTAIN_SCRIPTS__type" />
				<xsd:element name="CUSTOMERS" type="dflt:CUSTOMERS__type" />
				<xsd:element name="AUDIT_ITEMS" type="dflt:AUDIT_ITEMS__type" />
				<xsd:element name="LABELS" type="dflt:LABELS__type" />
				<xsd:element name="USERS" type="dflt:USERS__type" />
				<xsd:any namespace="PUBLIC" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== silesnet/sis-legacy/src/test/resources/cz/silesnet/dao/ServiceDAOTest.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../db-xsd/dataset.xsd">
    <!--Active-->
    <CUSTOMERS ID="10" HISTORY_ID="10" PUBLIC_ID="12345" INSERTED_ON="2010-05-19"
               NAME="bCustomer 1" COUNTRY="10" IS_ACTIVE="true" />
    <CUSTOMERS ID="11" HISTORY_ID="11" PUBLIC_ID="12346" INSERTED_ON="2010-05-19"
               NAME="aCustomer 2" COUNTRY="10" IS_ACTIVE="true" />
    <!--Inactive-->
    <CUSTOMERS ID="12" HISTORY_ID="12" PUBLIC_ID="12347" INSERTED_ON="2010-05-19"
               NAME="Customer 3" COUNTRY="10" IS_ACTIVE="false" />
    <!--PL-->
    <CUSTOMERS ID="13" HISTORY_ID="13" PUBLIC_ID="12348" INSERTED_ON="2010-05-19"
               NAME="Customer 4" COUNTRY="20" IS_ACTIVE="true" />

    <!--Active-->
    <SERVICES ID="10010001" CUSTOMER_ID="10" NAME="Service 1" PRICE="100" DOWNLOAD="2" UPLOAD="1" BPS="M"
              PERIOD_FROM="2010-01-01" STATUS="INHERIT_FROM_CUSTOMER" />
    <SERVICES ID="10010101" CUSTOMER_ID="10" NAME="Service 2" PRICE="100" DOWNLOAD="1" UPLOAD="1" BPS="M"
              PERIOD_FROM="2010-01-01" STATUS="INHERIT_FROM_CUSTOMER" />
    <SERVICES ID="10010201" CUSTOMER_ID="11" NAME="Service 3" PRICE="100" DOWNLOAD="1000" UPLOAD="1000" BPS="k"
              PERIOD_FROM="2010-01-02" PERIOD_TO="2010-12-31" STATUS="INHERIT_FROM_CUSTOMER" />
    <!--Inactive-->
    <SERVICES ID="10010301" CUSTOMER_ID="12" NAME="Service 4" PRICE="10" DOWNLOAD="1000" UPLOAD="500" BPS="k"
              PERIOD_FROM="2010-01-01" STATUS="INHERIT_FROM_CUSTOMER" />
    <!--PL-->
    <SERVICES ID="10010401" CUSTOMER_ID="13" NAME="Service 5" PRICE="100" DOWNLOAD="1000" UPLOAD="1000" BPS="k"
              PERIOD_FROM="2010-01-01" STATUS="INHERIT_FROM_CUSTOMER" />
    <!--Orphan-->
    <SERVICES ID="10010501" CUSTOMER_ID="0" NAME="Service 6" PRICE="1" DOWNLOAD="1" UPLOAD="1" BPS="M"
              PERIOD_FROM="2010-01-01" STATUS="INHERIT_FROM_CUSTOMER" />

    <NEWSERVICES ID="10010001" CUSTOMER_ID="0" CUSTOMER="Customer1" PERIOD_FROM="2012-01-11" />
    <NEWSERVICES ID="110010001" CUSTOMER_ID="0" CUSTOMER="Customer1" PERIOD_FROM="2012-01-11" />

</dataset>
